/**
 * LocalStorage Data Management and Static Catalog Integration
 * Reads designs from window.CATALOG_DATA generated by PowerShell,
 * uses LocalStorage for shopping cart, user account, category overrides, and admin settings.
 */

class Store {
    constructor() {
        this.STORAGE_KEY = 'stitch_thread_overrides'; // Store edits to price/title here since main data is static
        this.AUTH_ADMIN_KEY = 'stitch_thread_admin';
        this.AUTH_CLIENT_KEY = 'stitch_thread_client';
        this.CAT_KEY = 'stitch_thread_categories';
        this.CART_KEY = 'stitch_thread_cart';
        this.CLIENT_LIST_KEY = 'stitch_thread_registered_clients';
        this.ADMIN_CREDENTIALS_KEY = 'stitch_thread_admin_creds';
        
        // Initialize if empty
        if (!localStorage.getItem(this.STORAGE_KEY)) {
            localStorage.setItem(this.STORAGE_KEY, JSON.stringify({}));
        }
        if (!localStorage.getItem(this.CAT_KEY)) {
            const initialCategories = { 'general': 'General Designs' };
            localStorage.setItem(this.CAT_KEY, JSON.stringify(initialCategories));
        }
        if (!localStorage.getItem(this.CART_KEY)) {
            localStorage.setItem(this.CART_KEY, JSON.stringify([]));
        }
        if (!localStorage.getItem(this.CLIENT_LIST_KEY)) {
            localStorage.setItem(this.CLIENT_LIST_KEY, JSON.stringify([]));
        }
        if (!localStorage.getItem(this.ADMIN_CREDENTIALS_KEY)) {
            localStorage.setItem(this.ADMIN_CREDENTIALS_KEY, JSON.stringify({ username: 'admin', password: 'admin123' }));
        }
    }

    // --- Category Management ---
    getCategories() {
        return JSON.parse(localStorage.getItem(this.CAT_KEY)) || {};
    }

    addCategory(name) {
        const categories = this.getCategories();
        const id = name.toLowerCase().replace(/[^a-z0-9]/g, '-');
        if (!id) return false;
        
        categories[id] = name;
        localStorage.setItem(this.CAT_KEY, JSON.stringify(categories));
        return true;
    }

    deleteCategory(id) {
        let categories = this.getCategories();
        delete categories[id];
        localStorage.setItem(this.CAT_KEY, JSON.stringify(categories));
        return true;
    }

    // --- Factory Reset ---
    clearAllData() {
        localStorage.removeItem(this.STORAGE_KEY);
        localStorage.removeItem(this.CAT_KEY);
        localStorage.removeItem(this.CART_KEY);
        localStorage.removeItem(this.AUTH_CLIENT_KEY);
        localStorage.removeItem(this.CLIENT_LIST_KEY);
        // Re-initialize empty state
        localStorage.setItem(this.STORAGE_KEY, JSON.stringify({}));
        localStorage.setItem(this.CAT_KEY, JSON.stringify({}));
        localStorage.setItem(this.CART_KEY, JSON.stringify([]));
        localStorage.setItem(this.CLIENT_LIST_KEY, JSON.stringify([]));
        return true;
    }

    // --- Cart Management ---
    getCart() {
        return JSON.parse(localStorage.getItem(this.CART_KEY)) || [];
    }

    addToCart(designId) {
        const cart = this.getCart();
        if (!cart.includes(designId)) {
            cart.push(designId);
            localStorage.setItem(this.CART_KEY, JSON.stringify(cart));
            return true;
        }
        return false;
    }

    removeFromCart(designId) {
        let cart = this.getCart();
        cart = cart.filter(id => id !== designId);
        localStorage.setItem(this.CART_KEY, JSON.stringify(cart));
        return true;
    }

    clearCart() {
        localStorage.setItem(this.CART_KEY, JSON.stringify([]));
        return true;
    }

    // --- Design Management (Static + Overrides) ---
    getOverrides() {
        return JSON.parse(localStorage.getItem(this.STORAGE_KEY)) || {};
    }

    getAllDesigns() {
        // Read the static array generated by the PowerShell script
        const baseData = window.CATALOG_DATA || [];
        const overrides = this.getOverrides();
        
        // Merge in any admin edits (like price changes or category assignments)
        return baseData.map(d => {
            if (overrides[d.id]) {
                return { ...d, ...overrides[d.id] };
            }
            return d;
        });
    }

    getDesignById(id) {
        const designs = this.getAllDesigns();
        return designs.find(d => d.id === id);
    }

    searchDesigns(query = '', category = '') {
        let designs = this.getAllDesigns();
        
        if (category && category !== 'all') {
            designs = designs.filter(d => d.category === category);
        }
        
        if (query) {
            const lowerQuery = query.toLowerCase();
            designs = designs.filter(d => 
                d.id.toLowerCase().includes(lowerQuery) || 
                d.title.toLowerCase().includes(lowerQuery)
            );
        }
        
        return designs;
    }

    updateDesign(id, updatedFields) {
        // Since base data is static, we store edits in an overrides object
        const overrides = this.getOverrides();
        overrides[id] = { ...(overrides[id] || {}), ...updatedFields };
        localStorage.setItem(this.STORAGE_KEY, JSON.stringify(overrides));
        return true;
    }

    // Admin can 'hide' rather than delete since it's a physical file
    deleteDesign(id) {
        const overrides = this.getOverrides();
        overrides[id] = { ...(overrides[id] || {}), isHidden: true };
        localStorage.setItem(this.STORAGE_KEY, JSON.stringify(overrides));
        return true;
    }

    // --- Admin Authentication ---
    getAdminCredentials() {
        return JSON.parse(localStorage.getItem(this.ADMIN_CREDENTIALS_KEY));
    }

    updateAdminCredentials(newUsername, newPassword) {
        if (!newUsername || !newPassword) throw new Error("Username and Password cannot be empty");
        localStorage.setItem(this.ADMIN_CREDENTIALS_KEY, JSON.stringify({ username: newUsername, password: newPassword }));
        return true;
    }

    loginAdmin(username, password) {
        const creds = this.getAdminCredentials();
        if (username === creds.username && password === creds.password) {
            localStorage.setItem(this.AUTH_ADMIN_KEY, 'true');
            return true;
        }
        return false;
    }
    logoutAdmin() { localStorage.removeItem(this.AUTH_ADMIN_KEY); }
    isAdmin() { return localStorage.getItem(this.AUTH_ADMIN_KEY) === 'true'; }

    // --- GitHub CMS Integration ---
    getGithubConfig() {
        return JSON.parse(localStorage.getItem('stitch_thread_github')) || { token: '', repo: 'rajee-embroidery/rajee-embroidery.github.io' };
    }

    setGithubConfig(repo, token) {
        localStorage.setItem('stitch_thread_github', JSON.stringify({ repo, token }));
        return true;
    }

    fileToBase64(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => resolve(reader.result.split(',')[1]);
            reader.onerror = error => reject(error);
        });
    }

    b64EncodeUnicode(str) {
        return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
            function toSolidBytes(match, p1) {
                return String.fromCharCode('0x' + p1);
        }));
    }

    b64DecodeUnicode(str) {
        return decodeURIComponent(atob(str).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));
    }

    async uploadToGithub(file, designData) {
        const config = this.getGithubConfig();
        if (!config.token || !config.repo) {
            throw new Error("GitHub Integration not configured. Please set repository and token in Settings.");
        }

        const headers = {
            "Authorization": `token ${config.token}`,
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        };
        const baseUrl = `https://api.github.com/repos/${config.repo}/contents`;
        
        // 1. Upload original Image Base64
        const ext = file.name.split('.').pop();
        const cleanTitle = designData.title.replace(/[^a-zA-Z0-9-]/g, '-');
        const timestamp = new Date().getTime();
        const filename = `${cleanTitle}-${timestamp}.${ext}`;
        const designId = cleanTitle + '-' + timestamp;
        
        const base64Image = await this.fileToBase64(file);
        
        const imageRes = await fetch(`${baseUrl}/images/designs/${filename}`, {
            method: 'PUT',
            headers,
            body: JSON.stringify({
                message: `Upload design image: ${designId}`,
                content: base64Image
            })
        });
        
        if (!imageRes.ok) {
            const err = await imageRes.json();
            throw new Error(`Failed to upload image: ${err.message}`);
        }

        // 2. Fetch js/database.js
        let dbSha = null;
        let pCatalog = [];
        try {
            const dbGetRes = await fetch(`${baseUrl}/js/database.js`, { headers, method: 'GET' });
            if (dbGetRes.ok) {
                const dbDataUrl = await dbGetRes.json();
                dbSha = dbDataUrl.sha;
                const dbContentStr = this.b64DecodeUnicode(dbDataUrl.content);
                const match = dbContentStr.match(/window\.CATALOG_DATA\s*=\s*(\[.*\]);?/s);
                if (match && match[1]) {
                    pCatalog = JSON.parse(match[1]);
                }
            }
        } catch (e) {
            console.error("No existing database found or format error", e);
        }

        // 3. Append new item
        const newItem = {
            id: designId,
            title: designData.title,
            category: designData.category,
            price: designData.price,
            imageUrl: `images/designs/${filename}`,
            dateAdded: new Date().toISOString()
        };
        pCatalog.push(newItem);

        // Update local static data immediately for instant preview
        if (window.CATALOG_DATA) window.CATALOG_DATA.push(newItem);

        // 4. Update js/database.js
        const newDbContentStr = `window.CATALOG_DATA = ${JSON.stringify(pCatalog, null, 4)};`;
        const newDbBase64 = this.b64EncodeUnicode(newDbContentStr);

        const dbPutRes = await fetch(`${baseUrl}/js/database.js`, {
            method: 'PUT',
            headers,
            body: JSON.stringify({
                message: `Add design entry: ${designId}`,
                content: newDbBase64,
                sha: dbSha
            })
        });

        if (!dbPutRes.ok) {
            const err = await dbPutRes.json();
            throw new Error(`Failed to update database: ${err.message}`);
        }

        return true;
    }

    // --- Client Authentication & Profiles ---
    getAllClients() {
        return JSON.parse(localStorage.getItem(this.CLIENT_LIST_KEY)) || [];
    }
    
    loginClient(phone, name) {
        const profile = { name, phone };
        localStorage.setItem(this.AUTH_CLIENT_KEY, JSON.stringify(profile));
        
        // Add to global client registry for admin to see
        const clients = this.getAllClients();
        if (!clients.some(c => c.phone === phone)) {
            clients.push({ name, phone, dateJoined: new Date().toISOString() });
            localStorage.setItem(this.CLIENT_LIST_KEY, JSON.stringify(clients));
        }
        
        return true;
    }
    logoutClient() { localStorage.removeItem(this.AUTH_CLIENT_KEY); }
    getClientProfile() { return JSON.parse(localStorage.getItem(this.AUTH_CLIENT_KEY)); }
    isClient() { return !!localStorage.getItem(this.AUTH_CLIENT_KEY); }
    
    // Simulate finding similar image matching
    findSimilar(fileStr) {
        const designs = this.getAllDesigns().filter(d => !d.isHidden);
        if (designs.length === 0) return [];
        const shuffled = [...designs].sort(() => 0.5 - Math.random());
        return shuffled.slice(0, Math.min(3, designs.length));
    }
}

// Export to global scope
window.appStore = new Store();
